### ISSUE TITLE
Gcc 5 compatibility

### ISSUE THREAD

**Issue by Kalle72** [deu/palemoon-overlay#44] opened 2017-04-20 10:54 UTC
Hello,

after gentoo stabilizes gcc5 palemoon claims that one should not use it. 

If this should **not** be true, it would be nice if you could circumvent this message. However, if it should be true, palemoon should include gcc4 as dependency and tell portage to use it instead of gcc5 (if possible). 

Many thanks that you brought palemoon to gentoo!
Best regards 
Kalle

**Comment by ntnn** [comment] 2017-04-24 21:18
The major problem is that gcc4 will be probably be masked soon and gcc5 is already the default for new installs.
Personally I'd also rather see a warning instead of a failing `pkg_pretend`.

**Comment by groundflyer** [comment] 2017-04-30 08:30
I just have built the 27.3.0 release with gcc-5.4.0-r3 with these settings:
```
ac_add_options --enable-official-branding
export MOZILLA_OFFICIAL=1
 
mk_add_options MOZ_CO_PROJECT=browser
ac_add_options --enable-application=browser
 
mk_add_options MOZ_OBJDIR=/home/$USER/palemoon/build/
 
ac_add_options --enable-optimize="-O2 -msse2 -mfpmath=sse -march=native -pipe"
ac_add_options --with-pthreads
 
ac_add_options --disable-installer
ac_add_options --disable-updater
 
ac_add_options --enable-release
 
ac_add_options --enable-strip
 
ac_add_options --x-libraries=/usr/lib

ac_add_options --disable-pulseaudio
ac_add_options --disable-necko-wifi

ac_add_options --with-system-nspr
ac_add_options --with-system-libevent
ac_add_options --with-system-nss
ac_add_options --with-system-jpeg
ac_add_options --with-system-zlib
ac_add_options --with-system-bz2
ac_add_options --with-system-png
ac_add_options --enable-system-ffi
ac_add_options --with-system-libvpx
ac_add_options --enable-system-sqlite
ac_add_options --enable-system-cairo
ac_add_options --enable-system-pixman
ac_add_options --with-system-icu
```
It works, but I didn't test thoroughly, it fails to compile with `--enable-tests` flag.

**Comment by groundflyer** [comment] 2017-04-30 15:18
I upgraded my installation to 27.3.0 with flags: alsa dbus gtk2 official-branding optimize system-libs.
No crashes yet or other issues.

**Comment by deuiore** [comment] 2017-05-01 10:53
Sorry, but it still does not solve the crashes. As with the previous versions it might seem to be working fine from a summary test, but they still happen nonetheless.

I doubt the problems will be solved until the Pale Moon developers decide to address them directly and start targeting gcc 5.

**Comment by ntnn** [comment] 2017-05-01 11:53
@deuiore 
This is not about that the crashes are solved - this is that it is _not_ sensible at all to abort compilation if the user is on gcc4.

Gentoo users are reasonably technically skilled to know what they're getting into when they compile software with an unsupported compiler. An message via ewarn that gcc5 is not supported should be enough.

The compiler switching in the message in the palemoon-1 eclass is also _more_ prone to generate errors with palemoon instead of compiling the whole system with gcc5 - if you'd want to be on the safe side with palemoon you'd have to recompile the packages against which palemoon links with gcc4 as well, otherwise the ABI changes would create issues.

Please - at least add a use flag to enable compilers higher than gcc4; `unsupported-compiler` e.g.

As said before, gcc4 is on the best way to be masked in the tree and those who do use palemoon on gentoo will (and already do) just copy the ebuilds and eclasses to a local overlay to remove the gcc5 check.

**Comment by Kalle72** [comment] 2017-05-06 15:52
Hello again,

@deuiore: Sounds reasonable. But why should one care about gcc-5 at all if it is not supported by the moonchild guys and gcc-4 does the trick? Would it not be the best option if the ebuild uses gcc-4 as dependency and calls gcc-4 directly to compile pale moon. 

@ntnn: Why do you think that gcc-4 will be masked in the near future? Are there any strong hints for that? Even gcc-3 and the "ultra-old" gcc-2 are available in gentoo's main-tree today! Would be weird if gcc-4 goes away soon!

Best regards
Kalle

**Comment by ntnn** [comment] 2017-05-07 00:42
@Kalle72: That is being discussed on the gentoo-dev ml and it looks like
they're not going through with _all_ old gcc versions, keeping a few of the
newer gcc4 and mask everything earlier.

Additionally from the same thread `RFC: masking old versions of sys-devel/gcc`:
```
Except that "switching back" from gcc-5 to gcc-4 doesn't really work, and that
gcc-4 will happily use gcc-5 libraries, with unintended consequences.
```

Failing hard is imho not required - yes it may cause a more unstable build, but
moreso does using an application compiled with gcc4 when the rest is compiled
with gcc5. A warning is enough.

Explicitly depending on gcc:4 and using that for compilation is *bad* and
_will_ cause problems for the end user.

**Comment by Massimo-B** [comment] 2017-05-09 07:07
Some replies from the #palemoon. Because of only a few development resources at Moonchild especially for the Linux platform they are currently rewriting the multimedia subsystem at no.1 priority.  Main objective right now is Media Source Extensions and the multimedia system in general.

However the exact reason for the compiler issues are not discovered yet.
> 14 million lines of code is hard to debug for a compiler bug that compiles but produces unstable binaries.

So if anybody likes to debug to the cause of the issue, the PM devs would be happy to know about.

>  no other group besides Gentoo would have the unique experence to deal with GCC oddities

**Comment by deuiore** [comment] 2017-05-12 13:47
@ntnn: The difference is that I'm not talking theoretically here. At first building with gcc5 was allowed, then I started experiencing crashes, sometimes sudden and apparently inexplicable, other times I could see a pattern in them: i.e. when closing a tab after visiting certain pages. The behaviour in the latter case was consistent so it shouldn't be that hard to debug, but the Pale Moon developers don't really seem interested in that right now and I don't have the time, the knowledge, or the inclination to tackle the issue.
So no, a warning would not be enough.
Meanwhile I never had a problem with gcc4, even though I understand your concerns and I don't like the current situation at all either.

Anyway, I decided to compromise. When the next version comes out I'm thinking of adding the possibility for the user to set an environment variable (e.g. I_WANT_TO_COMPILE_PALEMOON_WITH_GCC5=1) to bypass the check,  in the spirit of something I've already seen done before with some Gentoo unstable ebuild releases.
I won't be supporting any issue that might arise from doing that though.

**Comment by nado** [comment] 2017-09-23 09:47
I have modified the eclass to use environment (/etc/portage/package.env and /etc/portage/env) to specify CC/CXX, I am trying to get palemoon-27.4.2 to compile on my system and will make a PR afterward.

I am also trying to get rid of some repoman errors as the current status makes it difficult to see real issues amongst all the warnings.

**Comment by kentfredric** [comment] 2017-12-16 00:10
As of Profile 17.0 , GCC < 6 becomes masked,

Additionally, -fPIC gets forced on globally and that further complicates things.

```
69:04.64 ../../build/unix/gold/ld: error: /var/tmp/portage/www-client/palemoon-27.6.2/work/palemoon-27.6.2/o/toolkit/library/../../media/libstagefright/Unified_cpp_media_libstagefright0.o: requires dynamic R_X86_64_PC32 reloc against '_Z13GetDemuxerLogv' which may overflow at runtime; recompile with -fPIC
69:04.64 ../../build/unix/gold/ld: error: read-only segment has dynamic relocations
69:04.64 /var/tmp/portage/www-client/palemoon-27.6.2/work/palemoon-27.6.2/media/libstagefright/binding/MoofParser.cpp:767: error: undefined reference to 'GetDemuxerLog()'
69:04.65 /var/tmp/portage/www-client/palemoon-27.6.2/work/palemoon-27.6.2/media/libstagefright/binding/MoofParser.cpp:759: error: undefined reference to 'GetDemuxerLog()'
69:04.65 /var/tmp/portage/www-client/palemoon-27.6.2/work/palemoon-27.6.2/media/libstagefright/binding/MoofParser.cpp:784: error: undefined reference to 'GetDemuxerLog()'
69:04.65 /var/tmp/portage/www-client/palemoon-27.6.2/work/palemoon-27.6.2/media/libstagefright/binding/MoofParser.cpp:789: error: undefined reference to 'GetDemuxerLog()'
69:04.65 collect2: error: ld returned 1 exit status
69:04.65 gmake[5]: *** [/var/tmp/portage/www-client/palemoon-27.6.2/work/palemoon-27.6.2/config/rules.mk:820: libxul.so] Error 1
69:04.65 gmake[4]: *** [/var/tmp/portage/www-client/palemoon-27.6.2/work/palemoon-27.6.2/config/recurse.mk:74: toolkit/library/target] Error 2
69:04.65 gmake[3]: *** [/var/tmp/portage/www-client/palemoon-27.6.2/work/palemoon-27.6.2/config/recurse.mk:37: compile] Error 2
69:04.65 gmake[2]: *** [/var/tmp/portage/www-client/palemoon-27.6.2/work/palemoon-27.6.2/config/rules.mk:541: default] Error 2
69:04.65 gmake[1]: *** [/var/tmp/portage/www-client/palemoon-27.6.2/work/palemoon-27.6.2/client.mk:399: realbuild] Error 2
69:04.65 gmake: *** [client.mk:171: build] Error 2
69:04.71 368 compiler warnings present.
69:07.19 Failed to parse ccache stats output: cache hit rate                      0.00 %
```

**Comment by deu** [comment] 2018-02-07 14:54
As of 2f31bfea466bd8457fe4b90a67725e92269a6aa5 it only takes an environment variable to use any compiler you choose.

**Closed by deu** 2018-02-07 14:54 UTC
