### ISSUE TITLE
Some icons are unset

### ISSUE THREAD

**Issue by nick87720z** [deu/palemoon-overlay#56] opened 2017-09-28 08:56 UTC
Some buttons and menu items have 'placeholder' icons.
This appears both with palemoon-bin, and now with compiled 27.4.2.

**Comment by nick87720z** [comment] 2017-09-28 09:13
It depends on used theme. 
It appears with all elementary icon themes, including elementary-xfce family and elementary+, as well as ePapirus.
But doesn't appear with e.g., Faenza-Darkest.

**Comment by deuiore** [comment] 2017-09-28 11:49
I can reproduce this problem, but only with palemoon-bin.

What I see when running it from the terminal are a sequence of these, one for every missing icon:
```(pale moon:6762): Gtk-WARNING **: Error loading theme icon 'gtk-cancel' for stock: Unable to load image-loading module: /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /usr/lib64/libxml2.so.2: undefined symbol: UCNV_TO_U_CALLBACK_STOP```

Emerging `dev-libs/libxml2` without the `icu` USE flag makes it go away and the icons show properly, but I have no idea why and I don't think forcing a dependency to `dev-libs/libxml2[-icu]` is a solution.

What should be tested is whether this is a problem isolated to Gentoo (using the official binary package) or not. If it isn't then the bug should be reported to upstream.

**Comment by nick87720z** [comment] 2017-09-29 10:47
So, it seems to happen with themes, using svg icons. Somewhere with libxml2, gdk-pixbuf and icu.
I found UCNV_TO_U_CALLBACK_STOP definition in icu-58.2, now trying to rebuild all 3 packages.

**Comment by deuiore** [comment] 2017-11-15 14:59
Could you try again with the latest ebuild? It seems to have been solved for me now (there have been changes made to ICU-related stuff).

**Comment by nick87720z** [comment] 2017-12-02 19:00
Just got working 27.6.1 during global world rebuild.
Some themes still not working, giving look, almost same as above. I ran through themes list, testing some more icon themes, here is result (did not surf for menu icons, only looked toolbars with above set):
**all good**: nouveGnome, Faenza Darkest, Obsidian-1, Ivy, Arc
**partially (only two icons on the left are set):** Antü Classic
**not fixed:**
- papirus
- vertex
- elementary
- elementary+
- La Capitaine
- High Contrast (using recent version from gnome-look for closer to complete dark-grey monochrome look)
- ACYLS
- Sardi (tried Ghost Flexible)

**Comment by nick87720z** [comment] 2017-12-18 17:30
Found reason - problem is in libxml2, build with icu support.
Described there:
https://forums-archive.eveonline.com/default.aspx?g=posts&m=6516395

**Comment by deu** [comment] 2018-02-07 15:49
That's exactly as I described above: https://github.com/deu/palemoon-overlay/issues/56#issuecomment-332812653.
Anyway, I don't know what to do about this other than what I proposed in that same comment, which is not really a solution.

**Comment by nick87720z** [comment] 2018-02-07 16:23
I upgraded palemoon to 27.7.1, and icu at the same time upgraded to 60.2, after 58.2-r1.
After all upgrades i finally began to rebuild world with recent binutils.

libxml2 and icu are already rebuild, but it seems i forgot to write libxml2 -icu flag to package.use, and from some time libxml2 was build again with icu support; palemoon still showes all icons with elementary and papirus themes, but looking to ebuild i don't see any xml world, like libxml2 dependency or system-libxml2 option.

**Comment by deu** [comment] 2018-04-05 04:59
An update on this issue: this is probably caused by discrepancies between the system provided and the Pale Moon provided ICU libraries, as discussed with Moonchild on IRC.
The "correct" behaviour is actually the one that breaks the icons, because that means that the Pale Moon ICU is being used, as intended. However if libxml2 (which is probably used by GTK somewhere) is built with ICU support then that tries to use the system ICU, and the disparity causes the issue.

In fact now that the `shared-js` USE flag has been enabled by default it started to happen when using the source ebuilds with the default configuration too, since the flag indirectly causes the Pale Moon provided ICU library to be used.

**Comment by nick87720z** [comment] 2018-04-05 17:49
For now I have libxml2-2.9.7 with icu (60.2), and palemoon-27.8.3 with all system-lib flags, shared-js and gtk2.
No problems with icons.

**Comment by deu** [comment] 2018-08-18 21:29
This issue seems to have gone away with version 28.
@nick87720z can you confirm?

**Comment by nick87720z** [comment] 2018-08-19 08:00
Though i already told it just before, i repeated again to be sure. Current palemoon 27.9.4, and libxml2 has icu use flag enabled, all since winter. Issue doesn't happen with any theme, i have installed. Does it need to be retried with palemoon 28.x?

Many themes are dublicated in different colors/substyles, i tried only single from each set.
I tried this list:
```
Adwaita Abstroph ACYLS Antu Arc Bellissim Cheser clarity-icon-theme_0.4.2 'Cold Night' elementary ElementaryDarkCrystal ePapirus Faenza 'Flat Remix' fullest20160823 Glass gnome Halcyon hicolor HighContrast Ivy la-capitaine-icon-theme Lila_HD_Blue Linux-Dark17 Lüv mate Mine Moka Monolit_0.4.1 mousey Nitrux noia nouveGnome nuvola nuvox Obsidian-1 oxygen Ozon revival Sardi Tango Ultra-Flat Vertex Vibrantly-Simple victory-icon-theme Xenta
```
Though i tried to skip xcursor-only themes, some still involved unthemed gnome icons.
Many are known to be just based on others, so ideally this list could be even shorter.

**Comment by deu** [comment] 2018-08-19 13:08
Well, I was still experiencing the problem in some cases, hence I asked.
I guess I'll close this then.

**Closed by deu** 2018-08-19 13:08 UTC
Labels: help wanted
